### PR TITLE
feat: viz

### PR DESCRIPTION
**Pull request by fundon**

### CODE REVIEW

**Comment by ishtms** [comment]
There was a missing semicolon before the new lines added in the start-test.sh, I've fixed it. 
Thanks @fundon

**Comment by fundon** [comment]
Thank you. You can update the results. :) @ishtms

**Comment by ishtms** [comment]
@fundon viz looks really fast! I'm doing a complete retest of all the frameworks, and will update the result in 10 minutes.

**Comment by ishtms** [comment]
@fundon Added a whole bunch of code to automate everything - all you need to do is edit the `config.json` file, no need to start multiple servers at all. The generation of readme.md is done automatically now with the command. 

Check the new [**Try it yourself**](https://github.com/ishtms/rust-framework-benchmarks#user-content-benchmarking-tool) section.

**Comment by fundon** [comment]
> no need to start multiple servers at all

Nice! I love that.

**Pull request merged**
